feat: Dark theme
tendermint/flutter pull request #281
Opened 2022-05-16 11:25 UTC by wal33d006

The Ignite template now supports dark theme.
There is a toggle inside settings which allows you to change theme. Right now the updated theme is not saved in preferences which is why if you selected a dark theme you won't get it back after you reopen the app.
This will be implemented in a separate PR after this one is merged.

2022-05-16 13:33 UTC, Zfinix commented
Awesomeeeee work👍👍👍

2022-05-16 13:33 UTC, Zfinix approved these changes
Great work @wal33d006

2022-05-17 09:15 UTC, andrzejchm requested changes

2022-05-17 09:15 UTC, andrzejchm commented on starport_template/lib/starport_app.dart
> +        themeData: themeStore.isDarkTheme ? CosmosTheme.darkThemeData : const CosmosThemeData(),
could we implement the suggestion from this comment first:
https://github.com/tendermint/flutter/pull/266#issuecomment-1118337803

Also, we could get rid of this discrepancy of having light theme in default constructor and dark theme in static field. instead, lets have separate constructors for those:
```dart
CosmosThemeData.light()
CosmosThemeData.dark()
```

then, we could specify this piece as:

```dart
Observer(
    builder: (context) => CosmosTheme(
        brightness: () => themeStore.isDarkTheme ? Brightness.dark : Brightness.light,
        // by default, CosmosTheme would have default params set up for light and dark theme, so we don't need to provide anything here
    )
)
```

and the `CosmosTheme` constructor:
```dart
const CosmosTheme({
    this.themeData = CosmosThemeData.light(),
    this.darkThemeData = CosmosThemeData.dark(),
    ...
})

2022-05-18 09:59 UTC, andrzejchm approved these changes

2022-05-18 09:59 UTC, merged