feat: Import wallet, Password generation
tendermint/flutter pull request #78
Opened 2021-08-04 10:52 UTC by wal33d006

2021-08-04 13:06 UTC, andrzejchm commented on starport_template/lib/utils/base_env.dart
> +final baseEnv = BaseEnv()
lets not make the field static here. you can create a `BaseEnv` instance while the app starts and set it as static field the same way the `walletsStore` is saved in `StarportApp` class

2021-08-04 13:07 UTC, andrzejchm commented on starport_template/lib/widgets/password_setup_sheet.dart
> +          padding: const EdgeInsets.symmetric(horizontal: 16.0),
Lets use `CosmosAppTheme.spacing*` field rather than magic number

2021-08-05 06:00 UTC, wal33d006 commented on starport_template/lib/stores/wallets_store.dart
> +    BaseEnv baseEnv,
✅

2021-08-05 06:00 UTC, wal33d006 commented on starport_template/lib/widgets/password_setup_sheet.dart
> +          padding: const EdgeInsets.symmetric(horizontal: 16.0),
✅

2021-08-05 06:00 UTC, wal33d006 commented on starport_template/lib/widgets/password_setup_sheet.dart
> +            },
✅

2021-08-05 06:00 UTC, wal33d006 commented on starport_template/lib/widgets/password_setup_sheet.dart
> +        onPressed: () => password != null ? widget.submitClicked(password!) : null,
✅

2021-08-06 07:00 UTC, andrzejchm requested changes

2021-08-06 09:23 UTC, wal33d006 commented on starport_template/lib/main.dart
> +    BaseEnv()
Just updated it. Let me know if it looks good

2021-08-06 10:19 UTC, andrzejchm approved these changes
🥇

2021-08-06 10:20 UTC, merged